---
permalink: install-setup/cluster-setup-afx.html
sidebar: sidebar
keywords: ai data engine, aide, cluster setup, afx, install, set up
summary: "As an ONTAP storage administrator, you can integrate AI Data Engine (AIDE) with your AFX system deployment. You can either set up AIDE as part of an initial AFX storage system deployment or add AIDE to an AFX cluster that's already been deployed and serving data. In both cases, you'll need to also complete the AIDE configuration after finishing the basic setup."
---

= Set up AI Data Engine
:icons: font
:imagesdir: ../media/

[.lead]
As an ONTAP storage administrator, you can integrate AI Data Engine (AIDE) with your AFX system deployment. You can either set up AIDE as part of an initial AFX storage system deployment or add AIDE to an AFX cluster that's already been deployed and serving data. In both cases, you'll need to also complete the AIDE configuration after finishing the basic setup.

== 1. Set up AIDE and integrate it with an AFX storage system

There are two ways to set up AIDE and integrate it with an AFX storage system. Select the option that's appropriate for your environment.

[NOTE]
Before setting up AIDE, make sure you have the data compute nodes installed and connected to the cluster switches. See link:../install-setup/aide-hardware-requirements.html[Install AIDE] for more information.

=== Set up AIDE with a new AFX cluster

If you're setting up AIDE as part of an initial AFX system deployment, the AIDE setup process is part of the standard AFX cluster setup workflow. During the ONTAP cluster setup, System Manager automatically discovers the connected DCNs and includes them as part of the cluster configuration. After that, you're ready to complete the AIDE configuration, including the required licensing and OIDC configuration.

=== Set up AIDE with an existing AFX cluster

If you're adding an AIDE cluster to an existing AFX storage system, you need to configure the data compute nodes and finish setting up your AIDE cluster.

==== Add the data compute nodes to the cluster

ONTAP dynamically detects the new data compute nodes connected to your cluster network and displays them in System Manager. You can link:../administer/dcn-add-node.html[Add Data Compute Nodes to an AI Data Engine cluster]. Also note the following:

* The data compute nodes must be physically connected to the cluster switches. Exactly three DCNs are required when creating an AIDE cluster.
* You must have sufficient IP addresses for the DCN network and other configuration information to configure the network. 

==== Finish setting up your AIDE cluster

After integrating the DCN nodes and completing the initial network configuration, you can finish setting up your new AIDE cluster. A welcome panel on the right side of the page displays the remaining configuration steps.

.Steps 

. Configure link aggregation groups and VLANs.
+
This step might be required based on your environment.

. Configure network protocols.

. Update data compute software.

. Configure data engine networking.

. Create intercluster network interfaces.
+
Perform this step if you intend to catalog remote data.

. Peer with other ONTAP storage systems.
+
Perform this step if you intend to catalog remote data.

. Add a data container.

. link:../workspaces/prepare-data-for-aide.html[Add a workspace].

. link:../install-setup/configure-oidc.html[Configure OIDC authentication].

== 2. Complete AIDE configuration

After your AIDE cluster is set up and integrated with the AFX storage system, you need to complete the AIDE configuration.

.Steps

. link:../install-setup/install-license-task.html[Add the required AIDE licenses].

. link:../install-setup/configure-oidc.html[Configure OIDC for AIDE authentication].
