---
permalink: install-setup/cluster-setup-afx.html
sidebar: sidebar
keywords: cluster setup, afx, ai data engine, aide, install, set up
summary: "Set up your AIDE cluster with an AFX storage system. You can set up AIDE as part of an initial AFX cluster deployment or add AIDE to an existing AFX cluster."
---

= Set up AI Data Engine
:icons: font
:imagesdir: ../media/

[.lead]
As an ONTAP storage administrator, you can integrate AI Data Engine (AIDE) with your ONTAP cluster. You can either set up AIDE as part of an initial AFX storage system deployment or add AIDE to an AFX cluster that's already been deployed and serving data. In both cases, you'll need to also complete the AIDE configuration after finishing the basic setup.

== 1. Set up AIDE and integrate it with an AFX storage system

There are two ways to set up AIDE and integrate it with an AFX storage system. Select the option that's appropriate for your environment.

[NOTE]
Before setting up AIDE, make sure you have the DX50 data compute nodes (DCNs) installed and connected to the cluster switches. See link:../install-setup/install-setup-workflow.html[Install your AIDE system] for more information.

=== Set up AIDE with a new AFX cluster

If you're setting up AIDE as part of an initial AFX system deployment, the AIDE setup process is part of the standard AFX cluster setup workflow. During the AFX cluster setup, System Manager automatically discovers the connected DCNs and includes them as part of the cluster configuration. After that, you're ready to complete the AIDE configuration, including the required licensing and OIDC configuration.

=== Set up AIDE with an existing AFX cluster

If you're adding a DCN cluster to an existing AFX storage system, you need to configure the DCN nodes and finish setting up your AIDE cluster.

==== Add the DCN nodes to the AIDE cluster

ONTAP dynamically detects the new DCNs connected to your cluster network and displays them in System Manager. You can link:../administer/dcn-add-node.html[Add Data Compute Nodes to an AI Data Engine cluster]. Also note the following:

* The data compute nodes must be physically connected to the cluster switches. Exactly three DCNs are required when creating an AIDE cluster.
* You must have sufficient IP addresses for the DCN network and other configuration information to configure the network. 

==== Finish setting up your AIDE cluster

After integrating the DCN nodes and completing the initial network configuration, you can finish setting up your new AIDE cluster. A welcome panel on the right side of the page displays the remaining configuration steps.

.Steps 

. Configure link aggregation groups and VLANs
+
This step might be required based on your environment.

. Configure network protocols

. Update data compute software 

. Configure data engine networking

. Create intercluster network interfaces
+
Perform this step if you intend to catalog remote data.

. Peer with other ONTAP storage systems
+
Perform this step if you intend to catalog remote data.

. Add a data container

. Add workspaces

. link:../install-setup/configure-oidc.html[Configure OpenID Connect for ONTAP AIDE]
+
You must configure OIDC authentication to access the AI Data Engine Console.

== 2. Complete AIDE configuration

After your AIDE cluster is set up and integrated with the AFX storage system, you need to complete the AIDE configuration.

.Steps

. Add the required AIDE licenses.
+
link:../install-setup/install-license-task.html[Install AIDE licenses in your AFX system]

. Configure OIDC for AIDE authentication.
+
link:../install-setup/configure-oidc.html[Configure OpenID Connect for ONTAP AIDE]
