---
permalink: install-setup/cluster-setup.html
sidebar: sidebar
keywords: aide, ontap, cluster setup, data compute node, dcn, data engine
summary: "You can optionally set up and integrate an AIDE cluster as part of deploying a new AFX cluster."
---

= Set up AIDE with a new AFX cluster
:icons: font
:imagesdir: ../media/

[.lead]
You can optionally set up and integrate an AIDE cluster as part of deploying a new AFX cluster.

[TIP]
If you need to integrate a new AIDE cluster with an existing AFX cluster, see link:../install-setup/setup-aide-existing-afx.html[Set up AIDE with an existing AFX cluster].

== 1. Prepare to set up your cluster

You need to prepare for cluster setup by learning about AIDE and preparing the environment.

=== Learn about AIDE and the setup process

You should understand the AIDE architecture and the cluster setup process before you begin. The following resources provide information about AIDE and the cluster setup workflow:

* link:../get-started/learn-about.html[Learn about your AI Data Engine system]
* link:../get-started/quick-start.html[Quick start for AI Data Engine]

=== Install the AIDE hardware

You need to have the AIDE Data Compute Nodes (DCNs) installed and connected to the AFX cluster storage network before setting up your AIDE cluster. See the following for details:

* link:../install-setup/install-setup-workflow.html[Install your AIDE system]

== 2. Set up your AIDE cluster

When integrating AIDE with a new AFX cluster, the setup process is part of the standard AFX cluster setup workflow. During the AFX cluster setup, System Manager automatically discovers connected DCNs and includes them in the cluster configuration. See the following for details:

https://docs.netapp.com/us-en/ontap-afx/install-setup/cluster-setup.html[Set up your AFX storage system ONTAP cluster^]

Also note the following:

* The DCN nodes must be physically connected to the cluster switches. Exactly three DCNs are required to create an AIDE cluster and expansion is not supported.
* You must have sufficient IP addresses for the DCN network and other configuration information to configure the network.

== 3. Complete the initial configuration

After the initial cluster setup, you can complete the AIDE configuration by setting up the required licenses and authentication. See the following for details:

* link:../install-setup/install-license-task.html[Install AIDE licenses in your AFX system]
* link:../install-setup/configure-oidc.html[Configure OpenID Connect for ONTAP AIDE]

== Related information

* link:../install-setup/install-network-reqs.html[Network requirements for your AIDE system]
* https://docs.netapp.com/us-en/ontap-afx/[AFX documentation^]
* link:../install-setup/setup-aide-existing-afx.html[Set up AIDE with a new AFX cluster]
