---
permalink: install-setup/cluster-setup.html
sidebar: sidebar
keywords: aide, ontap, cluster setup, data compute node, dcn, data engine
summary: "After your AIDE hardware has been installed, you can complete the ONTAP cluster setup. This process includes additional steps for Data Compute Nodes (DCNs) and Data Engine services."
---

= Set up your ONTAP AIDE cluster
:icons: font
:imagesdir: ../media/

[.lead]
After your AIDE hardware has been installed, you can complete the ONTAP cluster setup. This process includes additional configuration steps for Data Compute Nodes (DCNs).

Refer to the [AFX storage system ONTAP cluster setup documentation](https://docs.netapp.com/us-en/ontap-afx/install-setup/cluster-setup.html) for the standard ONTAP cluster setup workflow. The procedures below describe the additional requirements and configuration for AIDE clusters.

== About this task

AIDE clusters extend standard ONTAP clusters with DCNs to support AI data processing and cataloging. The setup process includes additional networking, validation, and configuration steps to ensure the DCNs are properly integrated and ready for AI workloads. 

== Perform initial AIDE cluster setup

.Before you begin

* The required number of DCNs (minimum 3, maximum 10) must be physically connected to the cluster switches.
* You must have sufficient IP addresses for the DCN network.  
  The required number of IP addresses is:  
  `number of DCNs + number of ONTAP nodes + 3`

.Steps
Complete the standard ONTAP cluster setup as described in the [AFX documentation](https://docs.netapp.com/us-en/ontap-afx/install-setup/cluster-setup.html). During this procedure, follow this additional procedure for AIDE DCN setup.

. Discover and validate Data Compute Nodes (DCNs). During cluster initialization, System Manager automatically discovers connected DCNs. The System Manager UI displays each DCN’s model and serial number. At least 3 DCNs must be connected. If only 1 or 2 are detected, System Manager will report an error and block cluster creation.
. Configure the DCN backend network.
.. Provide an IP range or ranges for the DCN nodes.
.. Provide the subnet mask for the DCN network.

. Assign DCNs to the cluster.
.. Add discovered DCNs to the cluster using System Manager.
.. If DCN software versions do not match the ONTAP cluster version, System Manager displays a warning.
.. You can rename DCNs before adding them if desired.

== Complete the AIDE cluster setup
Follow these steps after completing the initial ONTAP cluster setup to finalize the AIDE configuration.

.Steps
. From the "Finish setting up the cluster" guide, click "Configure data engine networking." Configure a single Data Engine service IP address for the cluster. This address is load-balanced across all DCN nodes and used for Data Engine services. You can add or edit the Data Engine service interface from the dashboard or the Data Engine card.

.What's next
After completing the AIDE cluster setup, you can proceed to link:../install-setup/install-license-task.html[install AIDE licenses] and link:../install-setup/configure-oidc.adoc[configure OpenID Connect (OIDC) authentication] for secure access to System Manager and Data Engine services.

//12-12-25 ontapdoc-3534