---
permalink: install-setup/cluster-setup.html
sidebar: sidebar
keywords: aide, ontap, cluster setup, data compute node, dcn, data engine
summary: ""
---

= Set up AIDE with a new AFX cluster
:icons: font
:imagesdir: ../media/

[.lead]
You can optionally set up an AIDE cluster as part of deploying a new AFX cluster.

[TIP]
If you need to integrate a new AIDE cluster with an existing AFX cluster, see link:../install-setup/setup-aide-existing-afx.html[Set up AIDE with an existing AFX cluster^] instead.

== Prepare to set up your cluster

xxx

=== Learn about AIDE and the setup process

You should understand the AIDE architecture and the cluster setup process before you begin. The following resources provide information about AIDE and the cluster setup workflow:

* link:../get-started/learn-about.html[Learn about your AI Daa Engine system]
* link:../get-started/quick-start.html[Quick start for AI Data Engine]

=== Install the AIDE hardware

Before setting up your AIDE cluster, you need to have the AIDE hardware installed and connected to the AFX cluster storage network. The AIDE hardware includes Data Compute Nodes (DCNs) which provide the AI data processing capabilities. See:

* link:../install-setup/install-setup-workflow.html[Install your AIDE system]

== Set up your AIDE cluster

When integrating AIDE with a new AFX cluster, the setup process is part of the standard AFX cluster setup workflow. During the AFX cluster setup, System Manager automatically discovers connected DCNs and includes them in the cluster configuration. See:

* link:../install-setup/cluster-setup.html[Set up your ONTAP AIDE cluster]

== Complete the initial AIDE configuration

After completing the initial cluster setup, you can complete the AIDE configuration by setting up the required licenses and authentication. See:

* link:../install-setup/install-license-task.html[Install AIDE licenses in your AFX system]
* link:../install-setup/configure-oidc.html[Configure OpenID Connect for ONTAP AIDE]

== Related information

xxx

//------------------------------------------------------------------------------
[.big.red]*--- Ben's content from here to the end of the page ---*

After your AIDE hardware has been installed, you can complete the AIDE cluster setup with ONTAP. 

//Refer to the link:https://docs.netapp.com/us-en/ontap-afx/install-setup/cluster-setup.html[AFX storage system ONTAP cluster setup documentation^] for the standard ONTAP cluster setup workflow. The procedures below describe the additional requirements and configuration for AIDE clusters.

AIDE clusters extend standard ONTAP AFX clusters with Data Compute Nodes (DCNs) to support AI data processing and cataloging. The setup process includes networking, validation, and configuration steps to ensure the DCNs are properly integrated and ready for AI workloads. 

== Perform initial AIDE cluster setup

Connect your laptop device to the AIDE cluster and set several global configuration values.

.Before you begin

* The required number of DCNs must be physically connected to the cluster switches. Exactly three DCNs are required to create an AIDE cluster, and expansion is not supported.
* You must have sufficient IP addresses for the DCN network and other information to appropriately configure the networking. See link:../install-setup/install-network-reqs.html[Network requirements for your AIDE system^] for details.
// plus 3 unused IPs

.About this task
During cluster initialization, System Manager automatically discovers connected DCNs. The System Manager UI displays each DCN's model and serial number.

.Steps
. Discover your cluster network.
.. Connect your laptop to the management switch and access the network computers and devices.
.. Open File Explorer.
.. Select *Network*; then right-click and select *Refresh*.
.. Select either ONTAP icon; then accept any certificates displayed on your screen.

. From System Manager, set the administrator password.
+
Provide and verify the password for the `admin` account and select *Continue*.

. Configure the storage system (cluster) name and management IP address, subnet, and gateway.

. Configure node management IP addresses for the storage nodes.

. Configure the DCN backend network:
.. Provide an IP range or ranges for the DCN nodes.
.. Configure the subnet mask for the DCN backend network.

. Configure the network services. Select *Continue*.
+
Define the details for your DNS and NTP servers.

. Optionally set up encryption.
+
You can define the details for cluster encryption. Select *Continue*.
+ 
NOTE: For information on how to create a cluster for a non-Windows environment, see link:https://docs.netapp.com/us-en/ontap/software_setup/setup-cluster.html[Create an ONTAP cluster and join nodes^].

.What's next

You'll be redirected to the System Manager sign-in page. Perform the steps described in <<Complete the AIDE cluster setup>>.

//Complete the standard ONTAP cluster setup as described in the link:https://docs.netapp.com/us-en/ontap-afx/install-setup/cluster-setup.html[AFX documentation^]. During this procedure, follow this additional procedure for AIDE DCN setup.

== Complete the AIDE cluster setup

Follow these steps after completing the initial ONTAP cluster setup to finalize the AIDE configuration.

.Before you begin

You'll need the following configuration details:

* VLAN
* NAS 
* S3 (if applicable)

.Steps

. Sign in to System Manager using the administrator account you provided during initial cluster setup. Notice the popup window at the top right with three configuration options.

. Select *VLAN and tagging* and select the network options appropriate for your environment.

. Select *Network Services* and configure the client access protocols for the default data SVM.

. Select *Data container* and create a volume or S3 bucket.
+
NOTE: See documentation on how to best link:../workspaces/prepare-data-for-aide.html[prepare data for AI Data Engine^].

. Navigate to *Cluster > Settings > Software Update* tab and check that the DCN nodes are running the latest software version. If not, update the DCN software.

. From the *Finish setting up the cluster* guide, select *Configure data engine networking.* 
+
Configure a single AI Data Engine service IP address for the cluster. This address is load-balanced across all DCN nodes and used for Data Engine services. You can add or edit the Data Engine service interface from the dashboard or the Data Engine card.

.What's next
After completing the AIDE cluster setup, you can proceed to link:../install-setup/install-license-task.html[install AIDE licenses] and link:../install-setup/configure-oidc.adoc[configure OpenID Connect (OIDC) authentication] for secure access to System Manager and Data Engine services.
//------------------------------------------------------------------------------