---
permalink: authentication/configure-oidc-for-aide-task.html
sidebar: sidebar
keywords: openid connect, oidc, authentication, aide, system manager, configure, oauth
summary: "You can use System Manager to configure OpenID Connect (OIDC) authentication for AI Data Engine (AIDE) clusters, enabling secure, centralized login via an external Identity Provider (IdP)."
---
= Configure OpenID Connect for AIDE
:icons: font
:imagesdir: ../media/

[.lead]
You can use System Manager to configure OpenID Connect (OIDC) authentication for AI Data Engine (AIDE) clusters, enabling secure, centralized login via an external Identity Provider (IdP).

OIDC must be configured to access the AI Data Engine console.
.About this task

OpenID Connect (OIDC) is an authentication protocol that allows users to log in to System Manager and the Data Engine console using an identity provider (IdP) for authentication. When OIDC is enabled, all web-based logins are redirected to your IdP for authentication.

* OIDC can be configured after cluster creation and is not part of the initial setup workflow.
* If you need to modify the OIDC configuration, you must first disable OIDC in System Manager, then edit and re-enable the configuration.
* Removing OIDC will revert System Manager to local ONTAP user authentication.

.Before you begin

* You must have administrator access to System Manager.
* The OIDC IdP must be configured and accessible.

.Step

. In System Manager, navigate to *Cluster* > *Settings*. Locate the OpenID Connect card.
+
. If OIDC is already configured, you can edit or disable the configuration. If OIDC is not configured, click the gear icon to start the setup.
. Under Configure OpenID Connect, enter the following details:
.. Provider
.. Issuer URI
.. JSON web key set URI
.. Authorization endpoint URI
.. Token endpoint URI
.. End session endpoint URI 
.. Access Token Issuer (optional)
+
. Under Client configuration, enter the following details:
.. Client ID
.. Remote user claim
.. Refresh interval
+
. Under Connection details, enter the following details:
.. Cluster IP address or FQDN
.. Outgoing proxy (optional)
+
. Under External role mapping, select existing role mapping or define a new role for the ONTAP `admin` user.

. Check "Enable now" and click Save. System Manager will refresh to apply the new authentication settings.
. Log in with your IdP credentials. Upon successful authentication, you will be returned to System Manager.

//12-11-25 ONTAPDOC-3534