---
permalink: install-setup/install-license-task.html
sidebar: sidebar
keywords: ai data engine, license, install, enable, add, aide, ai data engine, software, entitlement, keys, codes, cluster, administrator, nlf, add license, license key, metadata engine, aipvs, vectorization, guardrails
summary: "You can install AI Data Engine Engine licenses using System Manager."
---

= Install AIDE licenses in ONTAP
:icons: font
:imagesdir: ../media/

[.lead]
Install AI Data Engine Engine (AIDE) licenses using System Manager. There are two licenses for AIDE: The Metadata Engine Basic license that is typically factory-installed as part of the ONTAP One license and the "AIPVS — Vectorization and Guardrails" license that must be purchased and installed for each GPU in your data compute nodes (DCNs).

The first license enables the Metadata Engine functionality in ONTAP, while the second license unlocks advanced AI capabilities such as vectorization and guardrails for AI workloads.

.Before you begin
* Ensure you have admin credentials to log in to System Manager.
* Ensure that the cluster is running ONTAP 9.18.1 and later.
* Download each license file to an accessible location.

.About this task
You need one Metadata Engine Basic license per data compute node (DCN) and one "AIPVS — Vectorization and Guardrails" license for each GPU in your DCN.

Additionally, ensure you have obtained and installed any supplementary license files that support ONTAP functionality or cloud storage. These include Amazon S3, NFS, and SnapMirror licenses.
//contap-609777. Unclear if we need examples or full list of potential supplementary licenses.

.Steps

If you have already obtained your NetApp license files for AIDE, you can use System Manager to install them.

[role="tabbed-block"]
====
.System Manager
--
.. Select *Cluster* > *Settings*.
.. Under *Licenses*, review the list of installed licenses to confirm if the Metadata Engine Basic license is present.
.. To install a new license (such as "AIPVS — Vectorization and Guardrails"), select *Add* and browse to and choose the license file (.txt or .lic) you downloaded from NetApp.
.. Click *Add*.
.. After adding the license, verify that the new license appears in the *Licenses* list.
.. For "AIPVS — Vectorization and Guardrails", ensure that the number of installed licenses matches the number of GPUs in your DCN nodes.
--

.CLI
--
.. Add one or more license keys using the ONTAP CLI:
+
[source,cli]
----
system license add
----

The following example installs a license file from the local node:
----
system license add -use-license-file true
----
The following example adds a license key directly:
----
system license add -license-code AAAAAAAAAAAAAAAAAAAAAAAAAAAA
----

Refer to the link:https://docs.netapp.com/us-en/ontap-cli/system-license-add.html[system license add^] command in the ONTAP command reference for more details.
--
====



