---
sidebar: sidebar
permalink: install-setup/install-setup-requirements.html
keywords: aide, ai, data engine, ai data engine, dcn, data compute node, afx, afx 1k, install, setup, requirements, cautions, dx50
summary: Review the equipment needed and the lifting precautions for your AIDE data compute nodes.
---
= Installation requirements for AIDE systems
:icons: font
:imagesdir: ../media/

[.lead]
Review the equipment needed and the lifting precautions for your AIDE data compute nodes.

== Equipment needed for install
To install the data compute nodes for your AIDE system, you need the following equipment and tools. 

** AN existing AIDE compatible storage installation, such as the AFX 1K. 
+ 
NOTE: For information on installing the AFX 1K storage system, refer to the link:https://docs.netapp.com/us-en/ontap-afx/install-setup/install-setup-workflow.html[Install your AFX 1K storage system^].
** Access to a web browser to configure your data compute nodes
** Electrostatic discharge (ESD) strap 
** Flashlight
** Laptop or console with a USB/serial connection
** Phillips #2 screwdriver 

== Lifting precautions 
The data compute nodes are heavy. Exercise caution when lifting and moving these items.

=== AIDE data compute node weights 
Take the necessary precautions when moving or lifting your AIDE data compute node.

An AIDE data compute node can weigh up to 46.3 lbs (21Kg). To lift the data compute node, use two people or a hydraulic lift.

.Related information

*  https://library.netapp.com/ecm/ecm_download_file/ECMP12475945[Safety information and regulatory notices^]

.What's next?
After you've reviewed the hardware requirements, you link:prepare-hardware.html[prepare to install your AIDE system].

// 2024 Sept 23, ONTAPDOC 1922
