---
sidebar: sidebar
permalink: install-setup/prepare-hardware.html
keywords: aide, ai, data engine, ai data engine, dcn, data compute node, prepare, hardware installation, afx, afx 1k, dx50
summary: Prepare to install the AIDE system in your ONTAP environment and register the hardware to access support benefits. 
---
= Prepare to install your AIDE storage system
:icons: font
:imagesdir: ../media/

[.lead]
Prepare to install your AIDE system by getting the site ready, unpacking the boxes and comparing the contents of the boxes to the packing slip, and registering the system to access support benefits.

== Step 1: Prepare the site
To install your AIDE system, ensure that the site and the cabinet or rack that you plan to use meet specifications for your configuration.

.Steps

. Use https://hwu.netapp.com[NetApp Hardware Universe^] to confirm that your site meets the environmental and electrical requirements for your AIDE system.

. Make sure you have adequate cabinet or rack space for your AIDE data compute nodes, storage system, shelves, and switches:
+

** 1U for each AIDE data compute node
** 2U for each AFX controller node 
** 2U for each NX224 shelf
** 1U or 2U per switch, depending on switch model.

== Step 2: Unpack the boxes
After you’ve ensured that the site and the cabinet or rack that you plan to use for your AIDE data compute nodes meet the required specifications, unpack all boxes and compare the contents to the items on the packing slip.

.Steps

. Carefully open all the boxes and lay out the contents in an organized manner.

. Compare the contents you’ve unpacked with the list on the packing slip. If you find any discrepancies, record them down for further action. 

+
You can get your packing list by scanning the QR code on the side of the shipping carton.

+
The following items are some of the contents you might see in the boxes. 

+

[%rotate, grid="none", frame="none", cols="12,9,4"]
|===
|*Hardware*
|*Cables* |
a|* Bezel
* Storage system
* Rail kits with instructions 
* Storage shelf
* Cisco Nexus 9332D-GX2B or 9364D-GX2A switch
* Data compute node(s)
a|* Management Ethernet cables (RJ-45 cables)
* Network cables
* Power cords
* Storage cables 
* USB-C serial port cable |
|===



== Step 3: Register your storage system
After you’ve ensured that your site meets the requirements for your AIDE system specifications, and you’ve verified that you have all the parts you ordered, you should register your system.

.Steps

. Locate the serial numbers for your storage system. 
+
You can find the serial numbers in the following locations:

- On the packing slip
- In your confirmation email
- On each controller or for some systems, on the system management module of each controller
+
image::../media/drw_ssn_label.svg[Example of the system serial number,width=200]
+

. Go to the http://mysupport.netapp.com/[NetApp Support Site^].

. Determine whether you need to register your storage system:
+
[cols="1a,2a" options="header"]
|===
| If you are a...| Follow these steps...
a|
Existing NetApp customer
a|

 .. Sign in with your username and password.
 .. Select *Systems* > *My Systems*.
 .. Confirm that the new serial number is listed.
 .. If the serial number is not listed, follow the instructions for new NetApp customers.

a|
New NetApp customer
a|

 .. Click *Register Now*, and create an account.
 .. Select *Systems* > *Register Systems*.
 .. Enter the storage system's serial number and requested details.

Once NetApp approves your registration, you can download the required software. Approval takes up to 24 hours.
|===

.What's next?
After you've prepared to install your AFX 1K hardware, you link:install-switches.html[install the switches for your AIDE system].

