---
sidebar: sidebar
permalink: install-setup/setup-aide-existing-afx.html
keywords: 
summary: ""
---
= Set up AIDE with an existing AFX cluster
:icons: font
:imagesdir: ../media/

[.lead]
You can optionally set up and integrate an AIDE cluster with an existing AFX cluster.

[TIP]
If you need to set up AIDE and a new AFX cluster at the same time, see link:../install-setup/cluster-setup.html[Set up AIDE with a new AFX cluster^] instead.

== DCN discovery and initial network configuration

xxx

When you set up AIDE with an existing AFX cluster, the DCNs are not automatically discovered and included in the cluster configuration as part of the standard AFX cluster setup workflow. You need to perform additional steps to discover the DCNs and configure the network settings for the AIDE cluster.

== Finish setting up your cluster

xxx

== Related information

* https://docs.netapp.com/us-en/ontap-afx/[AFX documentation^]
* link:../install-setup/cluster-setup.html[Set up AIDE with a new AFX cluster]
