---
sidebar: sidebar
permalink: install-setup/setup-aide-existing-afx.html
keywords: 
summary: "You can optionally set up and integrate an AIDE cluster with an existing AFX cluster."
---
= Set up AIDE with an existing AFX cluster
:icons: font
:imagesdir: ../media/

[.lead]
You can optionally set up and integrate an AIDE cluster with an existing AFX cluster.

[TIP]
If you need to set up AIDE and a new AFX cluster together at the same time, see link:../install-setup/cluster-setup.html[Set up AIDE with a new AFX cluster].

== 1. Prepare to set up your cluster

You need to prepare for cluster setup by learning about AIDE and preparing the environment.

=== Learn about AIDE and the setup process

You should understand the AIDE architecture and the cluster setup process before you begin. The following resources provide information about AIDE and the cluster setup workflow:

* link:../get-started/learn-about.html[Learn about your AI Daa Engine system]
* link:../get-started/quick-start.html[Quick start for AI Data Engine]

=== 2. Install the AIDE hardware

Before setting up your AIDE cluster, you need to have the AIDE hardware installed and connected to the AFX cluster storage network. The AIDE hardware includes Data Compute Nodes (DCNs) which provide the AI data processing capabilities. See:

* link:../install-setup/install-setup-workflow.html[Install your AIDE system]

After the AIDE hardware has been installed, you can complete the AIDE cluster setup with ONTAP.

== 3. Add the DCN nodes to the AIDE cluster

After the AIDE hardware has been installed, you can add the DCN nodes to the AIDE cluster using ONTAP System  Manager. See link:..administer/dcn-add-node.html[Add Data Compute Nodes to an AI Data Engine cluster] for instructions on adding the nodes. Also note the following:

* The nodes must be physically connected to the cluster switches. Exactly three DCNs are required when creating an AIDE cluster. 
* You must have sufficient IP addresses for the DCN network and other configuration information to configure the network.

== 6. Finish setting up your cluster

After you have added the DCN nodes and completed the initial network configuration, you can finish setting up your AIDE cluster. A panel on the right side of the page displays the remaining configuration steps needed to complete the AFX cluster setup.

The steps with a check mark and the text grayed out have already been completed. You should focus on any of the steps with an arrow on the left and bold text need to be completed.

.Steps

. Configure link aggregation groups and VLANs
+
Based on your configuration, this step may be required for your environment.

. Configure network protocols

. Update data compute software

. Configure data engine networking

. Create intercluster network interfaces
+
This step is required if you plan to cataglog remote data.

== 5. Complete the initial configuration

After completing the initial cluster setup, you can complete the AIDE configuration by setting up the required licenses and authentication. See:

* link:../install-setup/install-license-task.html[Install AIDE licenses in your AFX system]
* link:../install-setup/configure-oidc.html[Configure OpenID Connect for ONTAP AIDE]

== Related information

* link:../install-setup/install-network-reqs.html[Network requirements for your AIDE system]
* https://docs.netapp.com/us-en/ontap-afx/[AFX documentation^]
* link:../install-setup/cluster-setup.html[Set up AIDE with a new AFX cluster]
