section: deploy
title: Deploy
entries:
  - title: Learn about AIDE deployment
    url: /deploy/deployment-overview.html
  - title: AIDE requirements
    url: /deploy/requirements.html
  - title: Deploy AIDE Lite
    url: /deploy/deploy-aide-lite.html
  - title: Deploy AIDE Enterprise
    url: /deploy/deploy-enterprise.html
  - title: Deploy AIDE for dark sites
    url: /deploy/deploy-dark-site.html
