---
sidebar: sidebar
permalink: workspaces/assign-users-to-workspace.html
keywords: aide, workspaces, assign users, user management, ai data engine
summary: "After you create a workspace, you can assign users to it who will work with AI resources within that workspace."
---
= Manage user access in AI Data Engine workspaces 
:icons: font
:imagesdir: ../media/

[.lead] 
The users you assign to a workspace can be data engineers, data scientists, or other roles depending on your organization's structure and needs. Users will use their credentials to log in to the AI Data Engine (AIDE) Console and access the data container resources within the assigned workspace.
//Guardrails will prevent them from seeing some select files

System Manager enables you to manage which users have access to AI Data Engine workspaces. You can add or remove users to control who can view, modify, and interact with workspace data and activities.

.Before you begin

* You need _storage administrator_ privileges to manage user access to workspaces.
* Confirm that the workspace has been created and is active in the Workspaces inventory.
* Confirm that all pertinent data containers have been added to the workspace and are accessible.
* Confirm OIDC is enabled and configured for the cluster. Role mapping from IdP to ONTAP roles must be completed for each relevant data engineer and data scientist IdP user or group.
//Needs a link to OIDC topic

.Steps

. Add a user to a workspace: 
.. In System Manager, navigate to *Data Engine > Workspaces*. 
.. Select the workspace name to open its details page. 
.. Go to the Users tab. 
.. Select the *Add* button to open the add users dialog. 
.. Enter the details of one or more users. Enter the details as a comma-separated list of local, SAML, AD domain, or OIDC users.
//need examples of user formats? 
.. Select *Add* to grant the user access to the workspace.

. Remove a user from a workspace: 
.. In the Users tab of the workspace details page, locate and select the user you want to remove. 
.. Select the *Remove* button. 
.. Confirm the removal in the dialog. 
.. The user will be immediately removed and their access to the workspace revoked.

.Result
Only users listed in the workspace's Users tab will be able to access and interact with workspace data and activities.

