---
sidebar: sidebar
permalink: workspaces/assign-users-to-workspace.html
keywords: aide, workspaces, assign users, user management, ai data engine
summary: "After you create a workspace, you can assign users to it who will work with AI resources within that workspace."
---
= Manage users in AI Data Engine workspaces 
:icons: font
:imagesdir: ../media/

[.lead] 
System Manager enables you to manage which users have access to AI Data Engine workspaces. You can add or remove users to control who can view, modify, and interact with workspace data and activities.

//a note about data engineer and data scientist user roles and permissions in AIDE might go here

.Before you begin

* Confirm that the workspace has been created and is visible in the Workspaces inventory.
* Confirm that data containers have been added to the workspace and are accessible.

.Steps

. Add a user to a workspace: 
.. In System Manager, navigate to *AI Data Engine > Workspaces*. 
.. Click the workspace name to open its details page. 
.. Go to the Users tab. 
.. Click the *Add* button to open the add user dialog. 
.. Enter the user name. 
.. Click *Add* to grant the user access to the workspace.

. Remove a user from a workspace: 
.. In the Users tab of the workspace details page, locate the user you want to remove. 
.. Click the *Remove* option in the action menu next to the user. 
.. Confirm the removal in the dialog. 
.. The user will be removed and their access to the workspace will be revoked.

.Result
You have successfully managed user access for your AI Data Engine workspace. Only users listed in the workspace's Users tab will be able to access and interact with workspace data and activities.

