---
sidebar: sidebar
permalink: workspaces/create-data-container.html
keywords: aide, workspaces, create data container, ai data engine
summary: "After you create a cluster, you can create a data container for the mounted volume containing data you intend to use with AI Data Engine."
---

= Set up a data container in AI Data Engine
:icons: font
:imagesdir: ../media/

[.lead]
//mostly ai fluff
After you create a cluster, you'll want to establish a data source that can be used as the data container for the mounted volume containing data you intend to use with AI Data Engine. The data container prepares the volume for use in workspaces and data collections. Assigned users can then be given access to workspaces and resources relevant to their AI workloads.

.Before you begin

* You need storage administer privileges to create data containers.

.Steps

. In System Manager, navigate to *AI Data Engine > Data Containers*.
. Select *Add* to open the *Add Data Container* dialog.
. Choose the mounted volume you want to use as a data container from the dropdown list.

. Add a data collection to the workspace:
.. In the workspace details page, go to the Data Collection tab.
.. Select the *Add* button to open the data collection dialog.
.. Enter the required information for the new data collection.
.. Select *Add* to associate the data collection with the workspace.