---
sidebar: sidebar
permalink: workspaces/create-workspace.html
keywords: aide, workspaces, create workspace, ai data engine
summary: "After you create a cluster, you can create workspaces and add data collections you intend to use with AI Data Engine."
---

= Set up a workspace in AI Data Engine
:icons: font
:imagesdir: ../media/

[.lead]
After you set up a cluster, you can set up a workspace. Workspaces allow you to segment data on the cluster, control data access for individuals, and exclude data that should not be exposed to the AI Data Engine.

If you are administering storage, you'll use System Manager to create and manage workspaces, and add data collections to support AI workloads. 

Strategies for workspace creation vary by organization. You might create workspaces based on teams, projects, data sensitivity levels, or other criteria relevant. For example, if you work in healthcare, you might segment clinical data into a workspace but leave out data pertaining to IT, legal, or other departments.

.About this task
Workspace creation is subject to system processing limits (typically up to 15 GB per day per cluster). If you create multiple workspaces in parallel or in quick succession, each workspace may take longer to process, and you may experience significant delays. Data collections and Retrieval-Augmented Generation (RAG) search capabilities become available only after the workspace creation process is fully complete. You can monitor the status of workspace creation from the Workspaces inventory page. For best results, avoid creating many workspaces at once if you need immediate access to these features.
//CONTAP-612354

.Before you begin

* You need _storage administer_ privileges to create workspaces and data collections.
* You've determined the remote and local data sources you intend to use with the workspace and with AI Data Engine.
* You've created at last one data container that can be used by the workspace, such as a volume or an S3 bucket.
+
NOTE: Ensure NFS is enabled on the volume but that the volume is not CIFS enabled. Workspaces only support volumes with NFS. Volumes with CIFS (SMB) are not supported with workspaces.

// CONTAP-517543
//Should more clusters be added/peered?

.Steps

. Create the workspace:
.. In System Manager, navigate to *Data Engine > Workspaces*.
.. Select *Add*.
.. In the *Add Workspace* dialog, select at least one available data container to associate with the workspace.
.. Configure https://docs.netapp.com/us-en/ontap-afx/protect-data/snapshot-replication.html#step-1-create-a-cluster-peer-relationship[peered clusters^] so that the data from those clusters can be accessed within the workspace:

//Needs more info on peered clusters. Should it be covered here fully, as AFX process, linked out to ONTAP docs, or just mentioned?

.. If you'd like to configure user access to the workspace, you can do that now or link:assign-users-to-workspace.html[wait until after the workspace is created].
.. Configure a refresh interval for the workspace data (for example, six hours).
.. Select *Continue*.
.. In the *Finalize workspace* dialog, enter a workspace name and description.
.. Select *Add* to create the workspace.
+
NOTE: The workspace creation process takes several minutes to hours to complete, depending on the associated dataset and its file count, file size, and other factors.

//table of estimated times?

It will show up in the Workspaces page in `Creating` state until the process is complete.

//.. (Optional) Choose guardrails from the dropdown. If a guardrail is disabled or in test mode, review any warning messages.

. Review workspace details:
.. After creation, the workspace appears in `ready` state on the *Workspaces* inventory page.
.. Review workspace details, including total size, and percentage of cluster capacity used.
.. Select the workspace name to open the details page.
.. In the Overview tab, view workspace details and associated data containers.

//. Add a data collection to the workspace:
//.. In the workspace details page, go to the Data Collection tab.
//.. Select the *Add* button to open the data collection dialog.
//.. Enter the required information for the new data collection.
//.. Select *Add* to associate the data collection with the workspace.

.Result
After creation, the workspace appears in `ready` state on the Workspaces inventory page.
Review workspace details, including total size, and percentage of cluster capacity used.

Metadata will be extracted automatically for all datasources and stored in a metadata catalog that users can use to locate the files they need for their projects. After you assign users to the workspace, they can access and interact with the workspace-affiliated data collections and resources for their AI workloads.

