---
sidebar: sidebar
permalink: administer/aide-node-replace.html
keywords: ai data engine, aide, data compute node, dcn, replace node, node replacement, cluster maintenance
summary: "You need to replace a data compute node (DCN) in your AI Data Engine (AIDE) cluster if it stops functioning or needs to be swapped due to hardware failure, upgrade, or maintenance. This ensures the AIDE cluster remains healthy and operational. The procedure can be performed without disrupting ongoing services."
---
= Replace a node in your AI Data Engine cluster
:icons: font
:imagesdir: ../media/

[.lead]
You need to replace a data compute node (DCN) in your AI Data Engine (AIDE) cluster if it stops functioning or needs to be swapped due to hardware failure, upgrade, or maintenance. This ensures the AIDE cluster remains healthy and operational. The procedure can be performed without disrupting ongoing services.

== Prepare to replace a node

There are several things to consider before replacing a node in your AIDE cluster.

=== Requirements

You'll need the following:

* User credentials with _storage administrator_ privileges
* Serial number for the new replacement node

=== Restrictions

You should be aware of the following restrictions when replacing a node in your AIDE cluster:

* Node replacement is only supported using the CLI and optionally the REST API.
* You cannot perform node replacement using System Manager.
* The new node should match the cluster's software version; ONTAP will update it if needed.
* The failed node must not be powered on while connected to the cluster network to avoid IP address conflicts.

== Replace a DCN node in your AIDE cluster

You can replace a DCN node in your AIDE cluster using the following procedure.

.Steps

. Physically remove the failed node
+
Power off and disconnect the node from the cluster network. Make sure the node is not booted up on the network during the replacement process.

. Delete the failed node from the cluster using the following command:
+
`dcn cluster node delete -name <node_name> -force true`
+
Provide the actual name for the <node_name> value.

. Physically attach the new node to the cluster
+
Make sure the node is cabled in, powered on, and discoverable.

. View the discoverable and unconfigured nodes to verify the new node is online:
+
`dcn cluster node show -membership available`

. Add the node to the cluster using the following command:
+
`dcn cluster node create -serial-number <new_node_serial>`
+
ONTAP will allocate an IP address for the new node. If the node's software version does not match the cluster, ONTAP will automatically update the node.

. Verify cluster health and node integration with either of the following commands:
+
`dcn cluster node show`
+
`dcn cluster node show -instance`

.Related information

* link:../administer/dcn-add-node.html[Expand your compute cluster]