---
sidebar: sidebar
permalink: administer/update-aide-firmware-software.html
keywords: update, firmware, system files, automatic updates, automated updates, aide, disable, 
summary: "Update DCN firmware and AI Data Engine Console software using ONTAP System Manager's automatic updates functionality or make updates manually."
---
= Update DCN firmware and AI Data Engine Console software
:icons: font
:imagesdir: ../media/

[.lead]
You can update data compute node (DCN) firmware, AI Data Engine Console software including vectorization and guardrails functionality, and other system files on your AI Data Engine system using ONTAP System Manager.

AIDE does not support automatic updates. By default, admins must download and install an update.

.Before you begin

* You need _storage administrator_ privileges to update DCN firmware and AI Data Engine software.
* link:upgrades-aide-summary.html#compatibility-matrix[Ensure compatibility between ONTAP, DCN firmware, and AI Data Engine software when planning updates]. AIDE software and ONTAP major versions must be compatible.

IMPORTANT: Revert functionality is not supported for DCN firmware or AI Data Engine software updates. After an update is installed, you cannot revert to a previous version.

.Steps

. Download the combined DCN firmware and AIDE software update file to a local client.
. In System Manager, select *Cluster > Settings*, then select *AI Data Engine updates*.
. Under Update software, select *Add AI Data Engine software files* and select the update package.
. After package upload is complete, select *Update* to begin installing updates on the DCN nodes.

.Result
The DCNs are updated with AI Data Engine software and the current version is displayed for each node.

.Related information

link:https://docs.netapp.com/us-en/ontap-afx/administer/upgrade-ontap.html[Upgrade ONTAP software^]