---
sidebar: sidebar
permalink: administer/upgrade-ontap-for-aide.html
keywords: update, firmware, system files, automatic updates, automated updates, aide
summary: "ONTAP software upgrades for AI Data Engine systems follow the same process as upgrades for other ONTAP systems and require similar preparation and procedures."
---
= Upgrade ONTAP for AI Data Engine systems
:icons: font
:imagesdir: ../media/

[.lead]
ONTAP software upgrades for AI Data Engine (AIDE) systems follow the same process as upgrades for other ONTAP systems. If you have an active SupportEdge contract for Active IQ Digital Advisor (also known as Digital Advisor), you should link:https://docs.netapp.com/us-en/ontap/upgrade/create-upgrade-plan.html[prepare to upgrade with Upgrade Advisor^]. Upgrade Advisor provides intelligence that helps you minimize uncertainty and risk by assessing your cluster and creating an upgrade plan specific to your configuration. If you don't have an active SupportEdge contract for Active IQ Digital Advisor, you should link:https://docs.netapp.com/us-en/ontap/upgrade/prepare.html[prepare to upgrade without Upgrade Advisor^].

After you prepare for your upgrade, it is recommended that you perform upgrades using link:https://docs.netapp.com/us-en/ontap/upgrade/task_upgrade_andu_sm.html[automated non-disruptive upgrade (ANDU) from ONTAP System Manager^]. ANDU takes advantage of ONTAP's high-availability (HA) failover technology to ensure that clusters continue to serve data without interruption during the upgrade.

Learn more about link:https://docs.netapp.com/us-en/ontap/upgrade/index.html[ONTAP software upgrades^]. 

IMPORTANT: Revert functionality is not supported for AFX software systems. After an upgrade is installed, you cannot revert to a previous version.

.Related information

link:upgrades-aide-summary.html#compatibility-matrix[Compatibility matrix for ONTAP, DCN firmware, and AI Data Engine software]