---
sidebar: sidebar
permalink: administer/view-insights.html
keywords: aide, aide system, insights, view insights
summary: "You can use the Insights feature of ONTAP System Manager to display suggested configuration updates that align with NetApp best practices. These changes can optimize the security and performance as well as other areas of your AIDE cluster."
---
= View Insights to optimize your AIDE storage system
:icons: font
:imagesdir: ../media/

[.lead]
You can use the _Insights_ feature of ONTAP System Manager to display suggested configuration updates that align with NetApp best practices. These changes can optimize the security and performance of your AIDE cluster.

//Cite cluster peering? For example, the Autonomous Ransomware Protection (ARP) feature is available with AIDE and provides anti-ransomware protection. Insights will inform you if ARP is not configured.

.About this task

Each of the insights is presented as a separate tile or card on the page that you can choose to implement or dismiss. You can also select the associated documentation link to learn more about a specific technology.

.Steps

. In System Manager, select *Analysis* and then *Insights*.
. Review the available recommendations.

.What's next

Perform any of the recommended actions to implement configuration best practices.
